// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_APcS4QlnhfTH5gmppsT-Rzxsv3wg7c',
    appId: '1:588687325743:web:affd335633d0b62a74a4da',
    messagingSenderId: '588687325743',
    projectId: 'just-aqua-2bc6a',
    authDomain: 'just-aqua-2bc6a.firebaseapp.com',
    storageBucket: 'just-aqua-2bc6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrfzLai9U2BW9fVoR-zRpINtkAu10PMN4',
    appId: '1:588687325743:android:6fa71e50292fc53f74a4da',
    messagingSenderId: '588687325743',
    projectId: 'just-aqua-2bc6a',
    storageBucket: 'just-aqua-2bc6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2jVlSKYTzSqH7oRHmnPBObf2RajMDl_4',
    appId: '1:588687325743:ios:b618d56ddf83016f74a4da',
    messagingSenderId: '588687325743',
    projectId: 'just-aqua-2bc6a',
    storageBucket: 'just-aqua-2bc6a.appspot.com',
    iosBundleId: 'com.example.justAqua01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2jVlSKYTzSqH7oRHmnPBObf2RajMDl_4',
    appId: '1:588687325743:ios:b618d56ddf83016f74a4da',
    messagingSenderId: '588687325743',
    projectId: 'just-aqua-2bc6a',
    storageBucket: 'just-aqua-2bc6a.appspot.com',
    iosBundleId: 'com.example.justAqua01',
  );
}
