// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Hl3jQhkgX1wf4b5mE5EaF2QOgu5VZL0',
    appId: '1:856358370049:web:4bc0e1dab44dda83c5b900',
    messagingSenderId: '856358370049',
    projectId: 'just-aqua-4de0e',
    authDomain: 'just-aqua-4de0e.firebaseapp.com',
    storageBucket: 'just-aqua-4de0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCpwojwvNfWbmT9ZOMAY6ZsuZ4oVQpC8',
    appId: '1:856358370049:android:62032d4a768a74bac5b900',
    messagingSenderId: '856358370049',
    projectId: 'just-aqua-4de0e',
    storageBucket: 'just-aqua-4de0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwNRaJLzqWY96osqRchQGS84EC6dN2L5o',
    appId: '1:856358370049:ios:fcb0bae59d076e64c5b900',
    messagingSenderId: '856358370049',
    projectId: 'just-aqua-4de0e',
    storageBucket: 'just-aqua-4de0e.appspot.com',
    iosBundleId: 'com.example.justAqua01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwNRaJLzqWY96osqRchQGS84EC6dN2L5o',
    appId: '1:856358370049:ios:fcb0bae59d076e64c5b900',
    messagingSenderId: '856358370049',
    projectId: 'just-aqua-4de0e',
    storageBucket: 'just-aqua-4de0e.appspot.com',
    iosBundleId: 'com.example.justAqua01',
  );
}
